image: f799/learning:latest
stages:
  - build
  - test
job1:
  stage: build
  script:
    - dotnet --version
    - dotnet --info
    - dotnet restore
    - pwd
    - ls -sl
    - chmod +x build.sh
    - ./build.sh
  only:
    - ci_test
  tags:
    - docker
