language: csharp
#sudo: required
#before_install:
#  - chmod +x build.sh
#mono:
#  - beta
#env:
#  - MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
os:
  - linux
#  - osx
script:
  - exist 0
#  - ./build.sh --quiet verify
