language: csharp
os:
  - osx
  - linux

# .NET CLI require Ubuntu 16.04
sudo: required
dist: xenial
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

# .NET CLI require OSX 10.10
osx_image: xcode8.3

mono:
  - 4.6.0

dotnet: 1.0.4

script:
  - chmod +x build.sh
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine
