version: 1.0.{build}
branches:
  only:
  - master
build_script:
- ps: .\build.ps1
test: off

image: Visual Studio 2017

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
#skip_commits:
#  # Regex for matching commit message
#  message: /docs.*/